image: nberlette/gitpod-enhanced

tasks:
  - before: pnpm install
    init: pnpm add -g vercel typescript tsm @types/node >/dev/null 2>&1
    command: pnpm lint --if-present

ports:
  - port: '3000-5000'
    onOpen: notify

gitConfig:
  commit.gpgsign: 'true'
  tag.gpgsign: 'true'

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addLabel: true
    addBadge: true
    addCheck: true

vscode:
  extensions:
    - github.copilot
    - github.vscode-codeql
    - eamodio.gitlens
    - cschleiden.vscode-github-actions
    - vsls-contrib.gistfs
    - simonsiefke.prettier-vscode
    - editorconfig.editorconfig
    - jock.svg
    - redhat.vscode-yaml
    - gamunu.vscode-yarn
    - jacano.vscode-pnpm
    - eg2.vscode-npm-script
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - davidanson.vscode-markdownlint
    - darkriszty.markdown-table-prettify
